apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      serviceAccountName: proxy-sa
      containers:
      - name: proxy
        image: METTIMI L'IMMAGINE GIUSTA 
        ports:
        - containerPort: 8080
