apiVersion: v1                                # crea un serviceAccount che poi posso associare ai pod (vedi file del deploymentil )
kind: ServiceAccount                          # nota che grazie a questo ServiceAccount, verrà montato un token diverso da quello di default
metadata:                                     # all'interno del container
  name: proxy-sa
---
apiVersion: rbac.authorization.k8s.io/v1      # indica che stiamo usando l'API rbac di kubernetes
kind: ClusterRole                             # ora è ClusterRole perchè vogliamo permessi a livello di cluster (non solo namespace)
metadata:                                     # quindi il proxy potrà agire su risorse di tutto il cluster
  name: proxy-role
rules:                                        # lista delle regole di autorizzazione
- apiGroups: [""]                             # vuoto significa /api/v1
  resources: ["pods"]                         # puoi agire sui pods
  verbs: ["get", "list", "delete"]                      # puoi eseguire get e list 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding                      # binding a livello di cluster (necessario per ClusterRole)
metadata:
  name: proxy-rolebinding
subjects:
- kind: ServiceAccount
  name: proxy-sa
  namespace: default                          # IMPORTANTISSIMO: va specificato il namespace del ServiceAccount
roleRef:
  kind: ClusterRole                           # colleghiamo un ClusterRole (non più Role)
  name: proxy-role
  apiGroup: rbac.authorization.k8s.io


# 3 kind, abbiamo 3 risorse collegate tra loro
# ServiceAccount=identità, Role=permessi, 
# RoleBinding= collegamento tra i due 

# per il discorso del token: creare un serviceAccount cambia appunto il token,
# una volta creato e specificato nel deployment, in fase di creazione del pod
# non gli verrà assegnato il token di default, ma quello relativo al SA.
# questo è indipendente dai permessi creati con Role. Infatti quello che succede
# è che prima l'API server vede chi sei è ti autentica (sei il ServiceAccount proxy-sa)
# e poi va a vedere quali sono i tuoi permessi e cosa puoi fare 

# i permessi probsbilmente li cambierò se il proxy deve inoltrare le richiete
# dei controller wasm