apiVersion: v1
kind: Service           # creiamo un service: oggetto che espone POD in rete
metadata:
  name: proxy-service   # nome del service ( posso usare come endpoint proxy-service.default.svc )
spec:
  selector:
    app: proxy          # dice inoltra il traffico ai pod con label app=proxy
  ports:
    - protocol: TCP
      port: 8080        # porta del service (tu manderai richieste quindi a proxy-service.default.svc:8080 e lui le inoltra al pod/container proxy alla porta)
      targetPort: 8080  # alla porta 8080


# il traffico viene inoltrato al pod, che normalmente ha un container e ok, ma se ne ha di più ??

#In Kubernetes, un Service non invia il traffico direttamente al container, ma al Pod. Il Pod è 
#l’unità di rete fondamentale: ha un proprio IP e tutte le richieste arrivano a quell’IP.
#Una volta che il traffico arriva al Pod, viene inoltrato alla porta specificata (targetPort). 
#A quel punto sarà il container che ascolta su quella porta a ricevere la richiesta.
#Se nel Pod ci sono più container, Kubernetes non fa alcuna selezione tra di essi: il traffico 
#viene inviato al Pod e poi raggiunge il container che sta ascoltando sulla porta indicata. 
#Questo significa che le porte dei container all’interno dello stesso Pod non devono entrare in conflitto.