apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: proxy-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proxy-rolebinding
subjects:
- kind: ServiceAccount
  name: proxy-sa
roleRef:
  kind: Role
  name: proxy-role
  apiGroup: rbac.authorization.k8s.io
